# Generated by Django 5.0.6 on 2025-02-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RegistroDia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bidon_15l', models.IntegerField(unique=True)),
                ('bidon_20l', models.IntegerField(unique=True)),
                ('precio', models.IntegerField(unique=True)),
                ('paga', models.IntegerField(unique=True)),
                ('debe', models.IntegerField(unique=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidones.cliente')),
            ],
        ),
    ]
