# Generated by Django 5.0.6 on 2025-02-11 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0002_remove_cliente_email_remove_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bidon_15l', models.IntegerField(unique=True)),
                ('bidon_20l', models.IntegerField(unique=True)),
                ('precio', models.IntegerField(unique=True)),
                ('paga', models.IntegerField(unique=True)),
                ('debe', models.IntegerField(unique=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidones.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroDia',
        ),
    ]
