# Generated by Django 5.0.6 on 2025-02-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0003_dia_delete_registrodia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='bidon_15l',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='bidon_20l',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='precio',
        ),
        migrations.AddField(
            model_name='dia',
            name='bidones_15L',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dia',
            name='bidones_20L',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dia',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dia',
            name='debe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dia',
            name='paga',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
