# Generated by Django 5.0.6 on 2025-02-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0005_cliente_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dia',
            old_name='bidones_15L',
            new_name='bidones_12L',
        ),
        migrations.AddField(
            model_name='dia',
            name='alquila',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='bidones_cliente',
        ),
    ]
