# Generated by Django 5.0.6 on 2025-02-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0007_rename_bidones_12l_dia_bidones_15l'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dia',
            name='alquila',
            field=models.IntegerField(default=0),
        ),
    ]
