# Generated by Django 5.0.6 on 2025-02-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0008_cliente_grupo_alter_dia_alquila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='grupo',
            field=models.IntegerField(unique=True),
        ),
    ]
