# Generated by Django 5.0.6 on 2025-02-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0009_alter_cliente_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='grupo',
            field=models.IntegerField(),
        ),
    ]
