# Generated by Django 5.0.6 on 2025-02-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0010_alter_cliente_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='alquila',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bidones_cantidad',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.CharField(default='No tiene observaciones.', max_length=100),
            preserve_default=False,
        ),
    ]
