# Generated by Django 5.1.6 on 2025-03-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidones", "0011_remove_dia_alquila_cliente_bidones_cantidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="dni",
            field=models.IntegerField(),
        ),
    ]
