# Generated by Django 5.0.6 on 2025-03-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidones', '0012_alter_cliente_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
    ]
